### ISSUE TITLE
AppData doesn't contain screenshots

### ISSUE THREAD

**Issue by danrabbit** [ChildishGiant/mixer#10]
The screenshot section of your appdata is blank. This should contain a link to a screenshot of your app using elementary OS default settings

**Comment by ChildishGiant** [comment]
Closed with 9be89d021bdb980d7ceb6e858cd769dbc41c59aa

**Comment by danrabbit** [comment]
It looks like you're not using elementary OS defaults in your screenshot, and it appears to have been taken on elementary OS 5. Make sure you're using default settings, including window control position. I'm fairly certain that running from Flatpak you'll also get the latest styles instead of the OS 5 style

**Comment by ChildishGiant** [comment]
> I'm fairly certain that running from Flatpak you'll also get the latest styles instead of the OS 5 style

Doesn't seem that way (I know I have the custom window controls there but still)
![image](https://user-images.githubusercontent.com/13716824/128244349-0767be48-7581-41f4-927a-04a8523e7368.png)

Either way, I'm pretty sure I've rectified this here 41e8385177c3122fc4ca58df4a77ea0f0cf84d65. Thanks for your seemingly never-ending patience with my mistakes :sweat_smile:

**Comment by danrabbit** [comment]
New screenshots look good! I'll keep checking for a new release and then I'll update the import PR whenever you're ready :)

**Comment by ChildishGiant** [comment]
All updated now! https://github.com/ChildishGiant/mixer/releases/tag/v0.1.3
