### ISSUE TITLE
Release tag doesn't contain a description

### ISSUE THREAD

**Issue by danrabbit** [ChildishGiant/mixer#11]
Your release tag should contain a description of changes since the last release. For your first release, it's okay to put something like "First release!", but it shouldn't be blank

**Comment by ChildishGiant** [comment]
Sorry to bother you but my release tabs are prepended with v (`v0.1.0` etc), should the release version in the xml reflect this or drop the v?

**Comment by ChildishGiant** [comment]
Closed with 9be89d021bdb980d7ceb6e858cd769dbc41c59aa
