### ISSUE TITLE
Create the AlertView manually instead of using Granite for Odin

### ISSUE THREAD

**Issue by Suzie97** [ChildishGiant/mixer#2]
Hey there, I was tweaking around with your app. As you might know, modern elementary OS apps, especially apps that don't have a lot going on in the headerbar use a flat headerbar. Like the new tasks app, time limit by marbetshcar, etc.

![Screenshot from 2021-07-20 09-44-27](https://user-images.githubusercontent.com/68198116/126260946-320da2b3-0849-47f9-9a9b-59926065c424.png)
This is Time Limit by marbetshcar

I tried implementing a flat header and this is how it looks
![Screenshot from 2021-07-20 09-40-28](https://user-images.githubusercontent.com/68198116/126260825-18e4c022-1dc6-41ff-870a-1e709ea678c2.png)

As you can see the window color and the background color of the Granite.AlertView dont match. So I would suggest the widget should be made manually. That way, the color will match with the headerbar and the rest of the window and the app should look modern.

Cheers!!

**Comment by Suzie97** [comment]
Just for more context, this is an app in which I manually made the `Granite.Widgets.Welcome` widget.

![Screenshot from 2021-07-20 09-46-53](https://user-images.githubusercontent.com/68198116/126261127-d7a9b136-f08d-415e-847e-1e72c637c0c7.png)

If the widget had not been manually made, the background would have been lighter than the rest of the window. I'm sorry I don't have screenshots for that.

**Comment by ChildishGiant** [comment]
Is this used officially or is it a style that some of the community like? I'm trying to keep with elementary styles. I do need to change to handy for those rounded bottom corners.

**Comment by Suzie97** [comment]
> Is this used officially or is it a style that some of the community like? I'm trying to keep with elementary styles. I do need to change to handy for those rounded bottom corners.

The only official apps that uses a flat headerbar is the new tasks app. But apps by Daniel Fore and Cassidy James themeselves use a flat headerbar. See dippi and harvey. Since they are simple apps, with nothing on the headerbar except for the window controls, so a flat headerbar looks nice and good.

**Comment by Suzie97** [comment]
@ChildishGiant , I made the alert view, rounded corners and flat headerbar but without handy.

![Screenshot from 2021-07-23 12-27-52](https://user-images.githubusercontent.com/68198116/126747670-2e8ba30c-7131-40e0-aaa2-dac2aaf5061f.png)

**Comment by ChildishGiant** [comment]
Closing in favour of ef6a26d7d5f98cbb47c6fed9609306965bfec9d7, which includes your AlertView but uses handy for rounded corners and flat style.
