### ISSUE TITLE
Absolutely love it !!! Simple and precise at what its supposed to do ...

### ISSUE THREAD

**Issue by aiamuzz** [ChildishGiant/mixer#32]
@ChildishGiant ... kudos for this simple and precise application.

The project suggests its a pretty new project only 5 months old ... Exactly what i was looking for.

Currently it runs as another application in the dock ... any possibility of evolving it into an applet that runs in the system tray ?

that would be just phenomenal as accessing it from the system tray will limit it to the systray bottom panel a more ideal spot to control such a utility ...

I am a designer ... if you want i could help you out with the design side of things ...

would love to hear from you ...

cheers.

**Comment by ChildishGiant** [comment]
I'm assuming you mean as a system indicator in the top right? I had a quick crack at that a while back but thought better to keep it as a standalone app, at least at first. Once I've finished rewriting the internals of this I might make it into an indicator as it should be easier after that. I also thought about merging it into the existing audio indicator but it's already quite full of options and I don't want to crowd it more. More discussion of this can be found at https://github.com/elementary/wingpanel-indicator-sound/issues/118
